CREATE TABLE stock_review_recent60 (
                              id int primary key auto_increment,
                              code char(16),
                              name varchar(64),
                              now float,
                              open float,
                              close float,
                              high float,
                              low float,
                              growthRate float,
                              createdAt timestamp,
                              upLimit float,
                              downLimit float,
                              marketValue float,
                              tradingMarketValue float,
                              pe float,
                              turnoverRate float,
                              type varchar(64),
                              industry varchar(64),
                              concepts varchar(1024),
                              bid1Money float,
                              upLimitType int,
                              everUpLimited int,
                              breakUpLimitCount int,
                              continuousUpLimitCount int,
                              upDownStatistics varchar(64),
                              firstUpLimitTime varchar(64),
                              finalUpLimitTime varchar(64),
                              volume float,
                              smallUp float default 0,
                              smallVolumeUp float default 0,
                              volumeBreakUpMa5 float default 0,
                              last2Up float default 0,
                              last3Up float default 0,
                              last5Up float default 0,
                              index stock_review_code_index(code)
);


CREATE TABLE stock_statistics (
                              id int primary key auto_increment,
                              code char(16),
                              priceMA5 float,
                              priceMA10 float,
                              priceMA20 float,
                              priceMA60 float,

                              volMA5 float,
                              volMA10 float,
                              volMA20 float,
                              volMA40 float,
                              volMA60 float,
                              volMA145 float,

                              priceCondition int default 0,
                              volCondition int default 0,
                              volContinueCondition int default 0,
                              last3UpRate float default 0,
                              last5UpRate float default 0,
                              last10UpRate float default 0,
                              last20UpRate float default 0,
                              breakUpRecent3HighestPrice int default 0,
                              breakUpRecent5HighestPrice int default 0,
                              breakUpRecent10HighestPrice int default 0,
                              breakUpRecent20HighestPrice int default 0,
                              profitLossRatio float default 0,
                              profitRate float default 0,
                              lossRate float default 0,
                              recentNowPrices text,
                              recentHighPrices text,
                              recentLowPrices text,
                              recentClosePrices text,
                              recentVolumes text,
                              createdAt timestamp default current_timestamp,

                              index stock_statistics_code_index(code)
);